### ISSUE TITLE
[gamma] CUDA 9 is not compatible with GCC version >=6 

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/BrainCaffe2#1]
```
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so.7)
CMake Error at cmake/public/cuda.cmake:321 (message):
  CUDA 9.0 is not compatible with std::tuple from GCC version >= 6.  Please
  upgrade to CUDA 9.2 or use the following option to use another version (for
  example):

    -DCUDA_HOST_COMPILER=/usr/bin/gcc-5

Call Stack (most recent call first):
  cmake/Dependencies.cmake:698 (include)
  CMakeLists.txt:219 (include)
```

**Comment by ys7yoo** [comment]
[QUICK FIX]
fixed by adding the following in `cmake/Dependencies.cmake` in line 698
```
  set(CUDA_HOST_COMPILER "/usr/bin/gcc-5")
```
